### ISSUE TITLE
How to use npm package on frontend

### ISSUE THREAD

**Issue by Koli14** [fernando-mc/serverless-finch#104]
I wan't to use a [polyglot](https://github.com/airbnb/polyglot.js) on my front-end. How can I add it?
I tried  `npm install node-polyglot`, and then `import 'node-polyglot'` in the top of my `main.js` file, but it was not working.

**Comment by StephaneP** [comment]
might want to use webpack or parcel to package your js

**Comment by fernando-mc** [comment]
Hi @Koli14! Thanks for using the plugin.

Similar to what @StephaneP suggests, I think you'll need to bundle the library in with your code and build your website in order to deploy it with serverless finch. Usually this involves some sort of `dist` directory being created.

I'm not sure if this question specifically applies to this plugin though so I'm closing it.
