### ISSUE TITLE
Not able to choose if I want bucket policy to be overwritten

### ISSUE THREAD

**Issue by nasirumair** [fernando-mc/serverless-finch#15]
This plugin always overwrites the bucket policy to make the bucket public, even if that is not needed. It would be nice to make that a parameter that can be passed in.

**Comment by fernando-mc** [comment]
@nasirumair The main purpose of the plugin is to push static website files. Usually, those need to be public in order to be used. 

Can you explain the use case you're looking for in more detail? Why do the files need to be otherwise? What specifically would you like to see happen when you use the plugin?

I'm hesitant to change the default behavior but maybe we can add a parameter to allow for a different policy on the files if there's a logical use case that makes sense for the plugin's purpose.

**Comment by nasirumair** [comment]
@fernando-mc The use case is that I have an existing policy on my bucket that allows only certain IPs to access the bucket. When I use this plugin, it overwrites that policy and makes the bucket public. If the bucket policy change was configurable and I could pass a parameter in to do that, this would be extremely helpful for sites needing more security

**Comment by fernando-mc** [comment]
@nasirumair seems like a use case that makes sense. If there was an optional param I guess you'd pass the policy in and have it applied instead of (or overwriting the default policy after the fact) to the bucket?

That would be fine as long as it didn't interfere with the existing behavior. I'm assuming from my personal experience that the expected and preferred default behavior is a public website but I'm not against supporting an optional custom policy like you describe.

Feel free to open a PR. I probably wont be able to write this on my own for a while. If you do write a PR please confirm that the default behavior is not broken.

**Comment by ajagnanan** [comment]
I saw #25 was created to address this. I'm running into the issue where I'm using Cloudfront to front the site, which doesn't require S3 to be public. Any reason why the pr was closed?

**Comment by fernando-mc** [comment]
@ajagnanan no idea. I think the person who opened it also closed it.

**Comment by fernando-mc** [comment]
@nasirumair @ajagnanan Please feel free to open a PR for this. I'm marking it as something we're open to. With version 2 of this plugin there was a lot of refactoring done so changes should be substantially easier to implement. I should be merging and publishing v2 today. Feel free to ask for help on this issue if you have questions!

**Comment by linusmarco** [comment]
V2 implements this functionality to some degree via CLI parameters (--no-policy-change, --no-cors-change). You still can't set a custom policy, but that's something we could implement down the road.

**Comment by fernando-mc** [comment]
Whoever picks this up can probably copy a lot of what was done and use that to guide the development for this feature.
