### ISSUE TITLE
Testing strategy

### ISSUE THREAD

**Issue by linusmarco** [fernando-mc/serverless-finch#29]
With the plugin growing pretty rapidly, @fernando-mc and I agree that it's going to be important to come up with a solid, standardized testing strategy.

I think that to start out we can do two things:
1. Try to get close to 100% unit test coverage for the current functionality (and aim for similar on any new code)
2. Standardize (and possibly automate parts of) the manual testing that @fernando-mc and other contributors do to make sure that the plugin properly deploys all objects and sets options as expected.

In the longer run, I think we should write proper end-to-end and integration tests to replace (2), but my opinion is that we can wait for now.

@fernando-mc, can you describe the process you currently use to test PRs--I think we can use that as a starting point for coming up with a standard battery of tests for (2).

I'm happy to spearhead the unit testing effort for (1), and work on (2) as well. Anyone else want to help out? @amsross @evanseeds  

We're hoping that formalizing this stuff will speed up the process of accepting new contributions and reduce the chance that anything breaks along the way.

**Comment by evanseeds** [comment]
I don't have much experience with unit testing, but if someone else could get a unit test framework set up, I would probably be able to write some unit tests. 

As far as the manual testing, the process I have is to clone the repo and put it into `./node_modules` in a test serverless project. It seems like a bad practice to me to manually put something in `./node_modules`, but as far as I can tell there's no other way to reference a plugin for serverless. @fernando-mc, do you have a better method?

**Comment by linusmarco** [comment]
Thanks for volunteering, @evanseeds! @fernando-mc already set up mocha for testing, but over the next week or so (estimate) I'll be working on adding a bunch of tests that you could use as examples as well. I'll also add a section to the README on how to run the unit tests.

In terms of the manual testing, you're right that it's a bad idea to manually copy the plugin to your node_modules. Luckily, though, the proper way is even easier :smiley:. Just follow this pattern in the `dependencies` section of your `package.json`:

```json
{
    "name": "serverless-test",
    "version": "1.0.0",
    "main": "index.js",
    "dependencies": {
        "serverless-finch": "file:/path/to/your/local/repo/serverless-finch"
    }
}
```

npm docs on local dependencies: https://docs.npmjs.com/files/package.json#local-paths

**Comment by amsross** [comment]
I would also add that linting would be a positive addition to automated testing. Close to 100% of the PRs are riddled with what would be pretty easily classifiable as style violations. Currently these all involve manual call-outs. 

Any of the dozens of popular linters can made this a one-line change.

```
"scripts": {
  "pretest": "standard",
  "test": "mocha test",
}
```

**Comment by amsross** [comment]
@linusmarco if you don't already have something in mind, a light restructuring of the current constructor implementation and a little `sinon.stub` here and there can make testing against AWS pretty trivial. Refactoring class methods which depend on `this` having a bunch of pre-configured state (such as `_processDeployment`) to make fewer assumptions can make that very achievable.

**Comment by linusmarco** [comment]
@amsross: I totally agree on adding a linter/formatter. I'm not a huge fan of standard because of the lack of config options--I would lean more towards prettier, but either would be a big step up from nothing.

Definitely makes sense to stub the AWS methods as part of the tests, and refactoring will make that a lot easier. Eventually it would be nice to have tests that actually deploy and then confirm the configuration in the deployed bucket, but that's what I was suggesting should be a longer-term goal because all that really adds is protection against changes in the AWS interface.

**Comment by fernando-mc** [comment]
@linusmarco @amsross All these suggestions sound great. 

Let's split into separate issues for any decisions that need to be made or code that needs to be written and then assign issues out among ourselves or by asking community members if they can tackle something.

Potential issues to split out here and discuss/prioritize separately
1. Choice of linter and how to implement it
2. What testing framework to use (I'm not tied to mocha)
3. Specific tests to write 
4. Specific structural improvements to make

Each of these should facilitate specific conversation and for most of them one or more PRs.

The main reason I want these issues split out is because we can then assign them out to collaborators to move forward with.

@evanseeds My review/testing process is super manual right now. Here's what I do:
1. Review the code with no tests for syntax/potential errors without running it
2. Wait for comments and updates from the contributor
3. When I'm satisfied with changes I pull down the pr code from github with `pr 10` for example to get pr 10. `pr` is aliased to this:
`alias pr='f() { git fetch origin && git checkout pr/"$1"; }; f'`
4. I build an npm package from the modified code with `npm pack`. This outputs a gzipped(?) file. 
5. I move the gzipped file to a test directory and install it with `npm install serverless-finch-long-name-withsomenumbers.gzip` 
6. Then in that same directory I have a sample serverless.yml file and multiple subdirectories with different index.html and error.html files. 
7. I run a series of `sls deploy` `sls remove` `sls deploy --region us-west-2` commands to try and emulate potential use cases.
8. I test that each command deploys/removes correctly.

**Comment by linusmarco** [comment]
@fernando-mc - I've broken out the topics identified in this thread into a few new issues (#32, #33, #34, #35, #36). I'm going to close this issue.
