### ISSUE TITLE
Upload static website files from custom directory

### ISSUE THREAD

**Issue by mebibou** [fernando-mc/serverless-finch#5]
Any way to upload files from the `./www` folder? I saw `distributionFolder` in the code but it seems to be joined to `client` parent folder. I'd like to be able to upload from the `www` folder in the root of the project

**Comment by fernando-mc** [comment]
@mebibou There isn't at the moment. Feel free to open a PR that adds this functionality and I will review and test it.  I've paused active development on many of my projects right now because of a few other commitments, Let me know if you have any questions.

Alternatively you can use this in combination with a bash script.

mkdir client
mv ./www ./client/dist
serverless client deploy
mv ./client/dist ./www
rmdir client

**Comment by fernando-mc** [comment]
@mebibou This is a great idea so I'm adding this as a potential enhancement. Please feel free to open a PR to add this otherwise I'll give this a shot another weekend.
