### ISSUE TITLE
Option to make AWS bucket content public rather than make a whole bucket public by bucket policy

### ISSUE THREAD

**Issue by joshpassenger** [fernando-mc/serverless-finch#69]
This is a: 

* [X] Feature request or change

### Current behaviour

Finch allows creation of public buckets by bucket policy change but this is actively frowned upon due to known issues in users adding private files to public buckets, individual objects that are public should be made public.

### Proposed behaviour

Add a flag that allows objects to be made public, this can be used in conjunction with the existing command line switches ---no-policy-change --no-config-change

### Justification

AWS currently warns users about buckets which are public via bucket policy, making objects public by ACL is much more granular and highly preferred.

**Comment by fernando-mc** [comment]
@joshpassenger Bucket policy appears to be the preferred method of giving public read permissions to a static site. https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html

I don't think I see ACL permissions for static sites anywhere? Maybe you can point me to the part of the docs that recommends ACLs so I can read more?

**Comment by joshpassenger** [comment]
Hi there, this can be done either as [objects are put into the bucket](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html):

    aws s3 cp index.html s3://mybucket/ --acl public-read

Or after the fact using [put-object-acl and specifying public-read](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object-acl.html):

    aws s3api put-object-acl --bucket mybucket --key index.html --acl public-read

My employer forbids the use of public S3 buckets by bucket policy.

**Comment by joshpassenger** [comment]
After deployment and using public objects you can then access the site over SSL using the url in the format:

https://<region>.amazonaws.com/<bucket>/index.html

If you don't rely static website hosting and use hashing for your routing strategy that is.

**Comment by joshpassenger** [comment]
As a work around is there a lifecycle hook for after serverless client deploy I could use to trigger a script using serverless-plugin-scripts?

I am already adding CORS to a bucket created from Lambda S3 event wiring using:

scripts:
    hooks:
      # Force a CORS policy onto the videos bucket via the AWS CLI
      'after:aws:deploy:deploy:updateStack': "aws s3api put-bucket-cors --profile transcribe --bucket ${self:custom.videoBucket} --cors-configuration file://config/s3-cors.json"

**Comment by fernando-mc** [comment]
Hi @joshpassenger thanks for asking about this - I'd like to be sure to clarify your use case here and I also wanted to give you some initial context first. The plugin's current focus is to help enable the deployment of static websites to S3. From what I understand, this implies that the entire content within a bucket will be public. That's my understanding from reachin over the AWS docs - https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteAccessPermissionsReqd.html

I think potentially you have a slightly divergent use case here that requires more constrained permissions? I'm not entirely sure that Serverless Finch is currently suited for supporting deploying other objects to S3 for the reasons you highlight - the permissions model is very permissive.  For a public static website all files in a bucket should be public so this behavior is _currently_ intentional. 

With all of that aside - Please let me know more about this use case so I can help figure out how we can best support your use case! Maybe we can still work on a PR to add a flag or configuration that supports some public objects and others non-public like you mention in your comments!

Other references that might be relevant for other contributors reviewing this later - Clarification about when to use ACLs - https://docs.aws.amazon.com/AmazonS3/latest/dev/access-policy-alternatives-guidelines.html

Thanks again! I think this could be a cool feature after we scope and we understand the use case a little better.

@linusmarco feel free to hop in here if you have thoughts too.

**Comment by joshpassenger** [comment]
Hi @fernando-mc I have a nice workaround now using the function below (sharing in case the implementation is interesting for you) so please just close this for now I agree I have a fairly narrow use case but I do expect public buckets to lose favour moving forward, just a heads up!

~~~~
var fs = require('fs');
var AWS = require('aws-sdk');
var credentials = new AWS.SharedIniFileCredentials({profile: 'myprofilename'});
AWS.config.credentials = credentials;
var s3 = new AWS.S3();

async function run () {

	try
	{
		var parameters = JSON.parse(fs.readFileSync('scripts/build-output-params.json'));

		console.log('Listing bucket: %s', parameters.WebBucket);

		var listParams = {
			Bucket: parameters.WebBucket
		};

		var objects = await s3.listObjects(listParams).promise();

		for (var i in objects.Contents)
		{
			var object = objects.Contents[i];
			console.log('Making public: s3://%s/%s', parameters.WebBucket, object.Key);

			var putACLParams = {
				Bucket: parameters.WebBucket,
				Key: object.Key,
				ACL: 'public-read'
			};

			var result = await s3.putObjectAcl(putACLParams).promise();
		}
	}
	catch (error)
	{
		console.log('[ERROR] Failed to make objects public', error);
		throw error;
	}
}

if (require.main == module)
{
	run();
}
~~~~

**Comment by fernando-mc** [comment]
@joshpassenger ok! Thanks for posting this in case it helps folks in the future. 

I think static websites are the exception that prove the rule in some senses in relation to S3 buckets because I agree that you want to restrict permissions as much as possible. In the case of static websites buckets though normally I assume the files are meant to be public. 

Thanks again for your thoughts here!
